package utils

class MatrizEstados{

    val array: Array<Array<Int?>> = Array(23, { _ -> arrayOfNulls<Int>(23)})

    init {
        set(0, Entrada.DIGITO.index, 2)
        set(0, Entrada.LETRA.index, 10)
        set(0, Entrada.PONTO.index, -1)
        set(0, Entrada.MAIS.index, 19)
        set(0, Entrada.MENOS.index, 19)
        set(0, Entrada.MULTI.index, 19)
        set(0, Entrada.DIV.index, 19)
        set(0, Entrada.MAIOR.index, 17)
        set(0, Entrada.MENOR.index, 15)
        set(0, Entrada.IGUAL.index, 16)
        set(0, Entrada.TAB.index, 13)
        set(0, Entrada.NOVA_LINHA.index, 13)
        set(0, Entrada.ASPAS.index, 8)
        set(0, Entrada.ABRE_CHAVE.index, 11)
        set(0, Entrada.FECHA_CHAVE.index, -1)
        set(0, Entrada.UNDERLINE.index, -1)
        set(0, Entrada.EOF.index, 14)
        set(0, Entrada.EXP.index, -1)
        set(0, Entrada.ABRE_PARENTESE.index, 20)
        set(0, Entrada.FECHA_PARENTESE.index, 21)
        set(0, Entrada.ESPACO.index, 13)
        set(0, Entrada.PONTO_VIGULA.index, 22)
        set(0, Entrada.ESPECIAL.index, -1)

        /*
        set(1, Entrada.DIGITO.index, 2)
        set(1, Entrada.LETRA.index, -1)
        set(1, Entrada.PONTO.index, -1)
        set(1, Entrada.MAIS.index, -1)
        set(1, Entrada.MENOS.index, -1)
        set(1, Entrada.MULTI.index, -1)
        set(1, Entrada.DIV.index, -1)
        set(1, Entrada.MAIOR.index, -1)
        set(1, Entrada.MENOR.index, -1)
        set(1, Entrada.IGUAL.index, -1)
        set(1, Entrada.TAB.index, -1)
        set(1, Entrada.NOVA_LINHA.index, -1)
        set(1, Entrada.ASPAS.index, -1)
        set(1, Entrada.ABRE_CHAVE.index, -1)
        set(1, Entrada.FECHA_CHAVE.index, -1)
        set(1, Entrada.UNDERLINE.index, -1)
        set(1, Entrada.EOF.index, -1)
        set(1, Entrada.EXP.index, -1)
        set(1, Entrada.ABRE_PARENTESE.index, -1)
        set(1, Entrada.FECHA_PARENTESE.index, -1)
        set(1, Entrada.ESPACO.index, -1)
        set(1, Entrada.PONTO_VIGULA.index, -1)
        set(1, Entrada.ESPECIAL.index, -1)
        */


        set(2, Entrada.DIGITO.index, 2)
        set(2, Entrada.LETRA.index, -1)
        set(2, Entrada.PONTO.index, 3)
        set(2, Entrada.MAIS.index, -1)
        set(2, Entrada.MENOS.index, -1)
        set(2, Entrada.MULTI.index, -1)
        set(2, Entrada.DIV.index, -1)
        set(2, Entrada.MAIOR.index, -1)
        set(2, Entrada.MENOR.index, -1)
        set(2, Entrada.IGUAL.index, -1)
        set(2, Entrada.TAB.index, -1)
        set(2, Entrada.NOVA_LINHA.index, -1)
        set(2, Entrada.ASPAS.index, -1)
        set(2, Entrada.ABRE_CHAVE.index, -1)
        set(2, Entrada.FECHA_CHAVE.index, -1)
        set(2, Entrada.UNDERLINE.index, -1)
        set(2, Entrada.EOF.index, -1)
        set(2, Entrada.EXP.index, 5)
        set(2, Entrada.ABRE_PARENTESE.index, -1)
        set(2, Entrada.FECHA_PARENTESE.index, -1)
        set(2, Entrada.ESPACO.index, -1)
        set(2, Entrada.PONTO_VIGULA.index, -1)
        set(2, Entrada.ESPECIAL.index, -1)


        set(3, Entrada.DIGITO.index, 4)
        set(3, Entrada.LETRA.index, -1)
        set(3, Entrada.PONTO.index, -1)
        set(3, Entrada.MAIS.index, -1)
        set(3, Entrada.MENOS.index, -1)
        set(3, Entrada.MULTI.index, -1)
        set(3, Entrada.DIV.index, -1)
        set(3, Entrada.MAIOR.index, -1)
        set(3, Entrada.MENOR.index, -1)
        set(3, Entrada.IGUAL.index, -1)
        set(3, Entrada.TAB.index, -1)
        set(3, Entrada.NOVA_LINHA.index, -1)
        set(3, Entrada.ASPAS.index, -1)
        set(3, Entrada.ABRE_CHAVE.index, -1)
        set(3, Entrada.FECHA_CHAVE.index, -1)
        set(3, Entrada.UNDERLINE.index, -1)
        set(3, Entrada.EOF.index, -1)
        set(3, Entrada.EXP.index, -1)
        set(3, Entrada.ABRE_PARENTESE.index, -1)
        set(3, Entrada.FECHA_PARENTESE.index, -1)
        set(3, Entrada.ESPACO.index, -1)
        set(3, Entrada.PONTO_VIGULA.index, -1)
        set(3, Entrada.ESPECIAL.index, -1)


        set(4, Entrada.DIGITO.index, 4)
        set(4, Entrada.LETRA.index, -1)
        set(4, Entrada.PONTO.index, -1)
        set(4, Entrada.MAIS.index, -1)
        set(4, Entrada.MENOS.index, -1)
        set(4, Entrada.MULTI.index, -1)
        set(4, Entrada.DIV.index, -1)
        set(4, Entrada.MAIOR.index, -1)
        set(4, Entrada.MENOR.index, -1)
        set(4, Entrada.IGUAL.index, -1)
        set(4, Entrada.TAB.index, -1)
        set(4, Entrada.NOVA_LINHA.index, -1)
        set(4, Entrada.ASPAS.index, -1)
        set(4, Entrada.ABRE_CHAVE.index, -1)
        set(4, Entrada.FECHA_CHAVE.index, -1)
        set(4, Entrada.UNDERLINE.index, -1)
        set(4, Entrada.EOF.index, -1)
        set(4, Entrada.EXP.index, 5)
        set(4, Entrada.ABRE_PARENTESE.index, -1)
        set(4, Entrada.FECHA_PARENTESE.index, -1)
        set(4, Entrada.ESPACO.index, -1)
        set(4, Entrada.PONTO_VIGULA.index, -1)
        set(4, Entrada.ESPECIAL.index, -1)


        set(5, Entrada.DIGITO.index, 7)
        set(5, Entrada.LETRA.index, -1)
        set(5, Entrada.PONTO.index, -1)
        set(5, Entrada.MAIS.index, 6)
        set(5, Entrada.MENOS.index, 6)
        set(5, Entrada.MULTI.index, -1)
        set(5, Entrada.DIV.index, -1)
        set(5, Entrada.MAIOR.index, -1)
        set(5, Entrada.MENOR.index, -1)
        set(5, Entrada.IGUAL.index, -1)
        set(5, Entrada.TAB.index, -1)
        set(5, Entrada.NOVA_LINHA.index, -1)
        set(5, Entrada.ASPAS.index, -1)
        set(5, Entrada.ABRE_CHAVE.index, -1)
        set(5, Entrada.FECHA_CHAVE.index, -1)
        set(5, Entrada.UNDERLINE.index, -1)
        set(5, Entrada.EOF.index, -1)
        set(5, Entrada.EXP.index, -1)
        set(5, Entrada.ABRE_PARENTESE.index, -1)
        set(5, Entrada.FECHA_PARENTESE.index, -1)
        set(5, Entrada.ESPACO.index, -1)
        set(5, Entrada.PONTO_VIGULA.index, -1)
        set(5, Entrada.ESPECIAL.index, -1)


        set(6, Entrada.DIGITO.index, 7)
        set(6, Entrada.LETRA.index, -1)
        set(6, Entrada.PONTO.index, -1)
        set(6, Entrada.MAIS.index, -1)
        set(6, Entrada.MENOS.index, -1)
        set(6, Entrada.MULTI.index, -1)
        set(6, Entrada.DIV.index, -1)
        set(6, Entrada.MAIOR.index, -1)
        set(6, Entrada.MENOR.index, -1)
        set(6, Entrada.IGUAL.index, -1)
        set(6, Entrada.TAB.index, -1)
        set(6, Entrada.NOVA_LINHA.index, -1)
        set(6, Entrada.ASPAS.index, -1)
        set(6, Entrada.ABRE_CHAVE.index, -1)
        set(6, Entrada.FECHA_CHAVE.index, -1)
        set(6, Entrada.UNDERLINE.index, -1)
        set(6, Entrada.EOF.index, -1)
        set(6, Entrada.EXP.index, -1)
        set(6, Entrada.ABRE_PARENTESE.index, -1)
        set(6, Entrada.FECHA_PARENTESE.index, -1)
        set(6, Entrada.ESPACO.index, -1)
        set(6, Entrada.PONTO_VIGULA.index, -1)
        set(6, Entrada.ESPECIAL.index, -1)


        set(7, Entrada.DIGITO.index, 7)
        set(7, Entrada.LETRA.index, -1)
        set(7, Entrada.PONTO.index, -1)
        set(7, Entrada.MAIS.index, -1)
        set(7, Entrada.MENOS.index, -1)
        set(7, Entrada.MULTI.index, -1)
        set(7, Entrada.DIV.index, -1)
        set(7, Entrada.MAIOR.index, -1)
        set(7, Entrada.MENOR.index, -1)
        set(7, Entrada.IGUAL.index, -1)
        set(7, Entrada.TAB.index, -1)
        set(7, Entrada.NOVA_LINHA.index, -1)
        set(7, Entrada.ASPAS.index, -1)
        set(7, Entrada.ABRE_CHAVE.index, -1)
        set(7, Entrada.FECHA_CHAVE.index, -1)
        set(7, Entrada.UNDERLINE.index, -1)
        set(7, Entrada.EOF.index, -1)
        set(7, Entrada.EXP.index, -1)
        set(7, Entrada.ABRE_PARENTESE.index, -1)
        set(7, Entrada.FECHA_PARENTESE.index, -1)
        set(7, Entrada.ESPACO.index, -1)
        set(7, Entrada.PONTO_VIGULA.index, -1)
        set(7, Entrada.ESPECIAL.index, -1)


        set(8, Entrada.DIGITO.index, 8)
        set(8, Entrada.LETRA.index, 8)
        set(8, Entrada.PONTO.index, 8)
        set(8, Entrada.MAIS.index, 8)
        set(8, Entrada.MENOS.index, 8)
        set(8, Entrada.MULTI.index, 8)
        set(8, Entrada.DIV.index, 8)
        set(8, Entrada.MAIOR.index, 8)
        set(8, Entrada.MENOR.index, 8)
        set(8, Entrada.IGUAL.index, 8)
        set(8, Entrada.TAB.index, 8)
        set(8, Entrada.NOVA_LINHA.index, 8)
        set(8, Entrada.ASPAS.index, 9)
        set(8, Entrada.ABRE_CHAVE.index, 8)
        set(8, Entrada.FECHA_CHAVE.index, 8)
        set(8, Entrada.UNDERLINE.index, 8)
        set(8, Entrada.EOF.index, -1)
        set(8, Entrada.EXP.index, 8)
        set(8, Entrada.ABRE_PARENTESE.index, 8)
        set(8, Entrada.FECHA_PARENTESE.index, 8)
        set(8, Entrada.ESPACO.index, 8)
        set(8, Entrada.PONTO_VIGULA.index, 8)
        set(8, Entrada.ESPECIAL.index, 8)


        set(9, Entrada.DIGITO.index, -1)
        set(9, Entrada.LETRA.index, -1)
        set(9, Entrada.PONTO.index, -1)
        set(9, Entrada.MAIS.index, -1)
        set(9, Entrada.MENOS.index, -1)
        set(9, Entrada.MULTI.index, -1)
        set(9, Entrada.DIV.index, -1)
        set(9, Entrada.MAIOR.index, -1)
        set(9, Entrada.MENOR.index, -1)
        set(9, Entrada.IGUAL.index, -1)
        set(9, Entrada.TAB.index, -1)
        set(9, Entrada.NOVA_LINHA.index, -1)
        set(9, Entrada.ASPAS.index, -1)
        set(9, Entrada.ABRE_CHAVE.index, -1)
        set(9, Entrada.FECHA_CHAVE.index, -1)
        set(9, Entrada.UNDERLINE.index, -1)
        set(9, Entrada.EOF.index, -1)
        set(9, Entrada.EXP.index, -1)
        set(9, Entrada.ABRE_PARENTESE.index, -1)
        set(9, Entrada.FECHA_PARENTESE.index, -1)
        set(9, Entrada.ESPACO.index, -1)
        set(9, Entrada.PONTO_VIGULA.index, -1)
        set(9, Entrada.ESPECIAL.index, -1)


        set(10, Entrada.DIGITO.index, 10)
        set(10, Entrada.LETRA.index, 10)
        set(10, Entrada.PONTO.index, -1)
        set(10, Entrada.MAIS.index, -1)
        set(10, Entrada.MENOS.index, -1)
        set(10, Entrada.MULTI.index, -1)
        set(10, Entrada.DIV.index, -1)
        set(10, Entrada.MAIOR.index, -1)
        set(10, Entrada.MENOR.index, -1)
        set(10, Entrada.IGUAL.index, -1)
        set(10, Entrada.TAB.index, -1)
        set(10, Entrada.NOVA_LINHA.index, -1)
        set(10, Entrada.ASPAS.index, -1)
        set(10, Entrada.ABRE_CHAVE.index, -1)
        set(10, Entrada.FECHA_CHAVE.index, -1)
        set(10, Entrada.UNDERLINE.index, 10)
        set(10, Entrada.EOF.index, -1)
        set(10, Entrada.EXP.index, -1)
        set(10, Entrada.ABRE_PARENTESE.index, -1)
        set(10, Entrada.FECHA_PARENTESE.index, -1)
        set(10, Entrada.ESPACO.index, -1)
        set(10, Entrada.PONTO_VIGULA.index, -1)
        set(10, Entrada.ESPECIAL.index, -1)


        set(11, Entrada.DIGITO.index, 11)
        set(11, Entrada.LETRA.index, 11)
        set(11, Entrada.PONTO.index, 11)
        set(11, Entrada.MAIS.index, 11)
        set(11, Entrada.MENOS.index, 11)
        set(11, Entrada.MULTI.index, 11)
        set(11, Entrada.DIV.index, 11)
        set(11, Entrada.MAIOR.index, 11)
        set(11, Entrada.MENOR.index, 11)
        set(11, Entrada.IGUAL.index, 11)
        set(11, Entrada.TAB.index, 11)
        set(11, Entrada.NOVA_LINHA.index, 11)
        set(11, Entrada.ASPAS.index, 11)
        set(11, Entrada.ABRE_CHAVE.index, 11)
        set(11, Entrada.FECHA_CHAVE.index, 12)
        set(11, Entrada.UNDERLINE.index, 11)
        set(11, Entrada.EOF.index, -1)
        set(11, Entrada.EXP.index, 11)
        set(11, Entrada.ABRE_PARENTESE.index, 11)
        set(11, Entrada.FECHA_PARENTESE.index, 11)
        set(11, Entrada.ESPACO.index, 11)
        set(11, Entrada.PONTO_VIGULA.index, 11)
        set(11, Entrada.ESPECIAL.index, 11)


        set(12, Entrada.DIGITO.index, -1)
        set(12, Entrada.LETRA.index, -1)
        set(12, Entrada.PONTO.index, -1)
        set(12, Entrada.MAIS.index, -1)
        set(12, Entrada.MENOS.index, -1)
        set(12, Entrada.MULTI.index, -1)
        set(12, Entrada.DIV.index, -1)
        set(12, Entrada.MAIOR.index, -1)
        set(12, Entrada.MENOR.index, -1)
        set(12, Entrada.IGUAL.index, -1)
        set(12, Entrada.TAB.index, -1)
        set(12, Entrada.NOVA_LINHA.index, -1)
        set(12, Entrada.ASPAS.index, -1)
        set(12, Entrada.ABRE_CHAVE.index, -1)
        set(12, Entrada.FECHA_CHAVE.index, -1)
        set(12, Entrada.UNDERLINE.index, -1)
        set(12, Entrada.EOF.index, -1)
        set(12, Entrada.EXP.index, -1)
        set(12, Entrada.ABRE_PARENTESE.index, -1)
        set(12, Entrada.FECHA_PARENTESE.index, -1)
        set(12, Entrada.ESPACO.index, -1)
        set(12, Entrada.PONTO_VIGULA.index, -1)
        set(12, Entrada.ESPECIAL.index, -1)


        set(13, Entrada.DIGITO.index, -1)
        set(13, Entrada.LETRA.index, -1)
        set(13, Entrada.PONTO.index, -1)
        set(13, Entrada.MAIS.index, -1)
        set(13, Entrada.MENOS.index, -1)
        set(13, Entrada.MULTI.index, -1)
        set(13, Entrada.DIV.index, -1)
        set(13, Entrada.MAIOR.index, -1)
        set(13, Entrada.MENOR.index, -1)
        set(13, Entrada.IGUAL.index, -1)
        set(13, Entrada.TAB.index, 13)
        set(13, Entrada.NOVA_LINHA.index, 13)
        set(13, Entrada.ASPAS.index, -1)
        set(13, Entrada.ABRE_CHAVE.index, -1)
        set(13, Entrada.FECHA_CHAVE.index, -1)
        set(13, Entrada.UNDERLINE.index, -1)
        set(13, Entrada.EOF.index, -1)
        set(13, Entrada.EXP.index, -1)
        set(13, Entrada.ABRE_PARENTESE.index, -1)
        set(13, Entrada.FECHA_PARENTESE.index, -1)
        set(13, Entrada.ESPACO.index, 13)
        set(13, Entrada.PONTO_VIGULA.index, -1)
        set(13, Entrada.ESPECIAL.index, -1)


        set(14, Entrada.DIGITO.index, -1)
        set(14, Entrada.LETRA.index, -1)
        set(14, Entrada.PONTO.index, -1)
        set(14, Entrada.MAIS.index, -1)
        set(14, Entrada.MENOS.index, -1)
        set(14, Entrada.MULTI.index, -1)
        set(14, Entrada.DIV.index, -1)
        set(14, Entrada.MAIOR.index, -1)
        set(14, Entrada.MENOR.index, -1)
        set(14, Entrada.IGUAL.index, -1)
        set(14, Entrada.TAB.index, -1)
        set(14, Entrada.NOVA_LINHA.index, -1)
        set(14, Entrada.ASPAS.index, -1)
        set(14, Entrada.ABRE_CHAVE.index, -1)
        set(14, Entrada.FECHA_CHAVE.index, -1)
        set(14, Entrada.UNDERLINE.index, -1)
        set(14, Entrada.EOF.index, -1)
        set(14, Entrada.EXP.index, -1)
        set(14, Entrada.ABRE_PARENTESE.index, -1)
        set(14, Entrada.FECHA_PARENTESE.index, -1)
        set(14, Entrada.ESPACO.index, -1)
        set(14, Entrada.PONTO_VIGULA.index, -1)
        set(14, Entrada.ESPECIAL.index, -1)


        set(15, Entrada.DIGITO.index, -1)
        set(15, Entrada.LETRA.index, -1)
        set(15, Entrada.PONTO.index, -1)
        set(15, Entrada.MAIS.index, -1)
        set(15, Entrada.MENOS.index, 18)
        set(15, Entrada.MULTI.index, -1)
        set(15, Entrada.DIV.index, -1)
        set(15, Entrada.MAIOR.index, 16)
        set(15, Entrada.MENOR.index, -1)
        set(15, Entrada.IGUAL.index, 16)
        set(15, Entrada.TAB.index, -1)
        set(15, Entrada.NOVA_LINHA.index, -1)
        set(15, Entrada.ASPAS.index, -1)
        set(15, Entrada.ABRE_CHAVE.index, -1)
        set(15, Entrada.FECHA_CHAVE.index, -1)
        set(15, Entrada.UNDERLINE.index, -1)
        set(15, Entrada.EOF.index, -1)
        set(15, Entrada.EXP.index, -1)
        set(15, Entrada.ABRE_PARENTESE.index, -1)
        set(15, Entrada.FECHA_PARENTESE.index, -1)
        set(15, Entrada.ESPACO.index, -1)
        set(15, Entrada.PONTO_VIGULA.index, -1)
        set(15, Entrada.ESPECIAL.index, -1)


        set(16, Entrada.DIGITO.index, -1)
        set(16, Entrada.LETRA.index, -1)
        set(16, Entrada.PONTO.index, -1)
        set(16, Entrada.MAIS.index, -1)
        set(16, Entrada.MENOS.index, -1)
        set(16, Entrada.MULTI.index, -1)
        set(16, Entrada.DIV.index, -1)
        set(16, Entrada.MAIOR.index, -1)
        set(16, Entrada.MENOR.index, -1)
        set(16, Entrada.IGUAL.index, -1)
        set(16, Entrada.TAB.index, -1)
        set(16, Entrada.NOVA_LINHA.index, -1)
        set(16, Entrada.ASPAS.index, -1)
        set(16, Entrada.ABRE_CHAVE.index, -1)
        set(16, Entrada.FECHA_CHAVE.index, -1)
        set(16, Entrada.UNDERLINE.index, -1)
        set(16, Entrada.EOF.index, -1)
        set(16, Entrada.EXP.index, -1)
        set(16, Entrada.ABRE_PARENTESE.index, -1)
        set(16, Entrada.FECHA_PARENTESE.index, -1)
        set(16, Entrada.ESPACO.index, -1)
        set(16, Entrada.PONTO_VIGULA.index, -1)
        set(16, Entrada.ESPECIAL.index, -1)


        set(17, Entrada.DIGITO.index, -1)
        set(17, Entrada.LETRA.index, -1)
        set(17, Entrada.PONTO.index, -1)
        set(17, Entrada.MAIS.index, -1)
        set(17, Entrada.MENOS.index, -1)
        set(17, Entrada.MULTI.index, -1)
        set(17, Entrada.DIV.index, -1)
        set(17, Entrada.MAIOR.index, -1)
        set(17, Entrada.MENOR.index, -1)
        set(17, Entrada.IGUAL.index, 16)
        set(17, Entrada.TAB.index, -1)
        set(17, Entrada.NOVA_LINHA.index, -1)
        set(17, Entrada.ASPAS.index, -1)
        set(17, Entrada.ABRE_CHAVE.index, -1)
        set(17, Entrada.FECHA_CHAVE.index, -1)
        set(17, Entrada.UNDERLINE.index, -1)
        set(17, Entrada.EOF.index, -1)
        set(17, Entrada.EXP.index, -1)
        set(17, Entrada.ABRE_PARENTESE.index, -1)
        set(17, Entrada.FECHA_PARENTESE.index, -1)
        set(17, Entrada.ESPACO.index, -1)
        set(17, Entrada.PONTO_VIGULA.index, -1)
        set(17, Entrada.ESPECIAL.index, -1)


        set(18, Entrada.DIGITO.index, -1)
        set(18, Entrada.LETRA.index, -1)
        set(18, Entrada.PONTO.index, -1)
        set(18, Entrada.MAIS.index, -1)
        set(18, Entrada.MENOS.index, -1)
        set(18, Entrada.MULTI.index, -1)
        set(18, Entrada.DIV.index, -1)
        set(18, Entrada.MAIOR.index, -1)
        set(18, Entrada.MENOR.index, -1)
        set(18, Entrada.IGUAL.index, -1)
        set(18, Entrada.TAB.index, -1)
        set(18, Entrada.NOVA_LINHA.index, -1)
        set(18, Entrada.ASPAS.index, -1)
        set(18, Entrada.ABRE_CHAVE.index, -1)
        set(18, Entrada.FECHA_CHAVE.index, -1)
        set(18, Entrada.UNDERLINE.index, -1)
        set(18, Entrada.EOF.index, -1)
        set(18, Entrada.EXP.index, -1)
        set(18, Entrada.ABRE_PARENTESE.index, -1)
        set(18, Entrada.FECHA_PARENTESE.index, -1)
        set(18, Entrada.ESPACO.index, -1)
        set(18, Entrada.PONTO_VIGULA.index, -1)
        set(18, Entrada.ESPECIAL.index, -1)


        set(19, Entrada.DIGITO.index, -1)
        set(19, Entrada.LETRA.index, -1)
        set(19, Entrada.PONTO.index, -1)
        set(19, Entrada.MAIS.index, -1)
        set(19, Entrada.MENOS.index, -1)
        set(19, Entrada.MULTI.index, -1)
        set(19, Entrada.DIV.index, -1)
        set(19, Entrada.MAIOR.index, -1)
        set(19, Entrada.MENOR.index, -1)
        set(19, Entrada.IGUAL.index, -1)
        set(19, Entrada.TAB.index, -1)
        set(19, Entrada.NOVA_LINHA.index, -1)
        set(19, Entrada.ASPAS.index, -1)
        set(19, Entrada.ABRE_CHAVE.index, -1)
        set(19, Entrada.FECHA_CHAVE.index, -1)
        set(19, Entrada.UNDERLINE.index, -1)
        set(19, Entrada.EOF.index, -1)
        set(19, Entrada.EXP.index, -1)
        set(19, Entrada.ABRE_PARENTESE.index, -1)
        set(19, Entrada.FECHA_PARENTESE.index, -1)
        set(19, Entrada.ESPACO.index, -1)
        set(19, Entrada.PONTO_VIGULA.index, -1)
        set(19, Entrada.ESPECIAL.index, -1)


        set(20, Entrada.DIGITO.index, -1)
        set(20, Entrada.LETRA.index, -1)
        set(20, Entrada.PONTO.index, -1)
        set(20, Entrada.MAIS.index, -1)
        set(20, Entrada.MENOS.index, -1)
        set(20, Entrada.MULTI.index, -1)
        set(20, Entrada.DIV.index, -1)
        set(20, Entrada.MAIOR.index, -1)
        set(20, Entrada.MENOR.index, -1)
        set(20, Entrada.IGUAL.index, -1)
        set(20, Entrada.TAB.index, -1)
        set(20, Entrada.NOVA_LINHA.index, -1)
        set(20, Entrada.ASPAS.index, -1)
        set(20, Entrada.ABRE_CHAVE.index, -1)
        set(20, Entrada.FECHA_CHAVE.index, -1)
        set(20, Entrada.UNDERLINE.index, -1)
        set(20, Entrada.EOF.index, -1)
        set(20, Entrada.EXP.index, -1)
        set(20, Entrada.ABRE_PARENTESE.index, -1)
        set(20, Entrada.FECHA_PARENTESE.index, -1)
        set(20, Entrada.ESPACO.index, -1)
        set(20, Entrada.PONTO_VIGULA.index, -1)
        set(20, Entrada.ESPECIAL.index, -1)


        set(21, Entrada.DIGITO.index, -1)
        set(21, Entrada.LETRA.index, -1)
        set(21, Entrada.PONTO.index, -1)
        set(21, Entrada.MAIS.index, -1)
        set(21, Entrada.MENOS.index, -1)
        set(21, Entrada.MULTI.index, -1)
        set(21, Entrada.DIV.index, -1)
        set(21, Entrada.MAIOR.index, -1)
        set(21, Entrada.MENOR.index, -1)
        set(21, Entrada.IGUAL.index, -1)
        set(21, Entrada.TAB.index, -1)
        set(21, Entrada.NOVA_LINHA.index, -1)
        set(21, Entrada.ASPAS.index, -1)
        set(21, Entrada.ABRE_CHAVE.index, -1)
        set(21, Entrada.FECHA_CHAVE.index, -1)
        set(21, Entrada.UNDERLINE.index, -1)
        set(21, Entrada.EOF.index, -1)
        set(21, Entrada.EXP.index, -1)
        set(21, Entrada.ABRE_PARENTESE.index, -1)
        set(21, Entrada.FECHA_PARENTESE.index, -1)
        set(21, Entrada.ESPACO.index, -1)
        set(21, Entrada.PONTO_VIGULA.index, -1)
        set(21, Entrada.ESPECIAL.index, -1)

        set(22, Entrada.DIGITO.index, -1)
        set(22, Entrada.LETRA.index, -1)
        set(22, Entrada.PONTO.index, -1)
        set(22, Entrada.MAIS.index, -1)
        set(22, Entrada.MENOS.index, -1)
        set(22, Entrada.MULTI.index, -1)
        set(22, Entrada.DIV.index, -1)
        set(22, Entrada.MAIOR.index, -1)
        set(22, Entrada.MENOR.index, -1)
        set(22, Entrada.IGUAL.index, -1)
        set(22, Entrada.TAB.index, -1)
        set(22, Entrada.NOVA_LINHA.index, -1)
        set(22, Entrada.ASPAS.index, -1)
        set(22, Entrada.ABRE_CHAVE.index, -1)
        set(22, Entrada.FECHA_CHAVE.index, -1)
        set(22, Entrada.UNDERLINE.index, -1)
        set(22, Entrada.EOF.index, -1)
        set(22, Entrada.EXP.index, -1)
        set(22, Entrada.ABRE_PARENTESE.index, -1)
        set(22, Entrada.FECHA_PARENTESE.index, -1)
        set(22, Entrada.ESPACO.index, -1)
        set(22, Entrada.PONTO_VIGULA.index, -1)
        set(22, Entrada.ESPECIAL.index, -1)

    }

    operator fun get(estado: Int, entrada: Entrada): Int? {
        return array[estado][entrada.index]
    }

    private operator fun set(estado: Int, entrada: Int, transicao: Int) {
        array[estado][entrada] = transicao
    }
}